### ISSUE TITLE
TODO: TS talk by netflix dude

### ISSUE THREAD

**Issue by marvincayetano** [marvincayetano/ts-noob#1]
- [ ] Analyze the talk
- [ ] Document the talk
- [ ] Try the code
